APPROVAL_SUBMIT = "APPROVAL_SUBMIT"
APPROVAL_APPROVE = "APPROVAL_APPROVE"
APPROVAL_REJECT = "APPROVAL_REJECT"

CONTRACT_SUBMIT = "CONTRACT_SUBMIT"
CONTRACT_APPROVE = "CONTRACT_APPROVE"
CONTRACT_REJECT = "CONTRACT_REJECT"

PLAN_CHANGE_SUBMIT = "PLAN_CHANGE_SUBMIT"
PLAN_CHANGE_APPROVE = "PLAN_CHANGE_APPROVE"
PLAN_CHANGE_REJECT = "PLAN_CHANGE_REJECT"

EVIDENCE_CREATE = "EVIDENCE_CREATE"
EVIDENCE_FILE_ADD = "EVIDENCE_FILE_ADD"
EVIDENCE_UPDATE = "EVIDENCE_UPDATE"
FILE_DOWNLOAD = "FILE_DOWNLOAD"

RISK_ACK = "RISK_ACK"

REPORT_EXPORT = "REPORT_EXPORT"

DRAFT_SAVE = "DRAFT_SAVE"
SUBMIT = "SUBMIT"

WBS_CHANGE_REQUEST_SAVE_DRAFT = "WBS_CHANGE_REQUEST_SAVE_DRAFT"
WBS_CHANGE_REQUEST_SUBMIT = "WBS_CHANGE_REQUEST_SUBMIT"

PACKAGE_SUBMIT = "PACKAGE_SUBMIT"
PACKAGE_APPROVE = "PACKAGE_APPROVE"
PACKAGE_REJECT = "PACKAGE_REJECT"

ADJUSTMENT_CREATE = "ADJUSTMENT_CREATE"
ADJUSTMENT_SUBMIT = "ADJUSTMENT_SUBMIT"
ADJUSTMENT_APPROVE = "ADJUSTMENT_APPROVE"
ADJUSTMENT_REJECT = "ADJUSTMENT_REJECT"
