# Generated by Django 5.2.10 on 2026-01-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectcontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('planned', 'Planned'), ('active', 'Active'), ('closed', 'Closed')], default='planned', max_length=20),
        ),
    ]
