# Generated by Django 5.2.10 on 2026-01-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_status'),
        ('projects', '0003_budgetitem'),
    ]

    operations = [
    ]
