# Generated by Django 5.2.10 on 2026-01-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_wbsitem'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='budgetitem',
            new_name='projects_bu_project_186f23_idx',
            old_name='projects_bu_project_6f9e5b_idx',
        ),
        migrations.RenameIndex(
            model_name='wbsitem',
            new_name='projects_wb_project_892322_idx',
            old_name='projects_wb_project_8f0f1c_idx',
        ),
    ]
