# Generated by Django 5.2.10 on 2026-01-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_projects_bu_project_6f9e5b_idx_projects_bu_project_186f23_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcontract',
            name='project',
        ),
        migrations.RemoveField(
            model_name='wbsitem',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='wbsitem',
            name='project',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('closed', 'Closed')], default='planned', max_length=20),
        ),
        migrations.DeleteModel(
            name='BudgetItem',
        ),
        migrations.DeleteModel(
            name='ProjectContract',
        ),
        migrations.DeleteModel(
            name='WBSItem',
        ),
    ]
