# Generated by Codex on 2026-01-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0001_initial"),
        ("projects", "0012_project_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="WBSChangeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role_snapshot", models.CharField(blank=True, default="", max_length=50)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("design_contract_change", "DESIGN_CONTRACT_CHANGE"),
                            ("schedule_adjustment", "SCHEDULE_ADJUSTMENT"),
                        ],
                        default="schedule_adjustment",
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "DRAFT"),
                            ("submitted", "SUBMITTED"),
                            ("approved", "APPROVED"),
                            ("rejected", "REJECTED"),
                            ("canceled", "CANCELED"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("base_version", models.IntegerField(default=1)),
                ("proposed_version", models.IntegerField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_wbs_changes",
                        to="auth.user",
                    ),
                ),
                (
                    "change_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracts.contractchange",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auth.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WBSChangeLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.IntegerField(default=0)),
                ("task_name", models.CharField(max_length=255)),
                ("weight", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_end", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="projects.wbschangerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="wbschangeline",
            index=models.Index(fields=["request", "order"], name="projects_wb_request_6b1c3a_idx"),
        ),
    ]
