# Generated by Django 5.2.10 on 2026-01-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_wbs_change_request'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='budgetitem',
            new_name='projects_bu_project_83b1ff_idx',
            old_name='projects_bu_project_cost_item_idx',
        ),
        migrations.RenameIndex(
            model_name='wbschangeline',
            new_name='projects_wb_request_3d7589_idx',
            old_name='projects_wb_request_6b1c3a_idx',
        ),
        migrations.RenameIndex(
            model_name='wbsitem',
            new_name='projects_wb_project_892322_idx',
            old_name='projects_wb_project_8f0f1c_idx',
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('planned', 'Planned'), ('active', 'Active'), ('closed', 'Closed')], default='planned', max_length=20),
        ),
    ]
