# Generated by Django 5.2.10 on 2026-01-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_approval_package'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='approvalpackageitem',
            new_name='projects_ap_package_2176e5_idx',
            old_name='projects_ap_package_3a20c6_idx',
        ),
    ]
