# Generated by Django 5.2.10 on 2026-05-29 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_rename_projects_ap_package_3a20c6_idx_projects_ap_package_2176e5_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budgetitem',
            name='uq_budgetitem_project_costitem',
        ),
    ]
