# Generated by Django 5.2.10 on 2026-08-24 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projectassignment_assignment_type'),
        ('projects', '0021_alter_project_legal_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contracting_license',
            field=models.ForeignKey(blank=True, help_text='계약 체결에 적용한 법인 면허입니다.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_projects', to='core.legalentitylicense'),
        ),
        migrations.AddField(
            model_name='project',
            name='contracting_license_snapshot',
            field=models.CharField(blank=True, default='', help_text='프로젝트 등록 시점의 면허명·등록번호·등록처 보존값입니다.', max_length=300),
        ),
    ]
