# Generated by Django 5.2.10 on 2026-08-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projectassignment_assignment_type'),
        ('projects', '0022_project_contracting_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contracting_licenses',
            field=models.ManyToManyField(blank=True, help_text='복합 공종 계약에 적용한 모든 법인 면허입니다.', related_name='multi_license_contract_projects', to='core.legalentitylicense'),
        ),
        migrations.AddField(
            model_name='project',
            name='work_types',
            field=models.JSONField(blank=True, default=list, help_text='계약상 실제 공종 목록입니다. project_type은 기존 호환을 위한 대표 공종입니다.'),
        ),
    ]
