# Generated by Django 5.2.10 on 2026-08-26 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_warehouse_legal_entity'),
        ('projects', '0023_project_contracting_licenses_project_work_types'),
        ('schedule', '0007_dailyprogress_rejection_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkProgressMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_mode', models.CharField(choices=[('QUANTITY', '물량 자동계산'), ('MANUAL', '수기 진행률')], default='MANUAL', max_length=12)),
                ('planned_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_progress_mappings', to='projects.project')),
                ('schedule_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_progress_mappings', to='schedule.scheduletask')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.uom')),
                ('wbs_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_progress_mappings', to='projects.wbsitem')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'is_active'], name='projects_pr_project_274133_idx'), models.Index(fields=['schedule_task', 'is_active'], name='projects_pr_schedul_4b9694_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'wbs_item', 'schedule_task'), name='uq_project_wbs_schedule_mapping'), models.CheckConstraint(condition=models.Q(('planned_qty__gte', 0)), name='chk_project_work_progress_mapping_planned_qty_nonnegative')],
            },
        ),
    ]
