from django.urls import include, path

from .web_views import (
    cbs_alias_add,
    cbs_alias_delete,
    cbs_alias_set_primary,
    cbs_aliases_view,
    cbs_create,
    cbs_edit,
    cbs_edit_name,
    cbs_list_view,
    cbs_toggle_active,
    hq_cbs_request_detail,
    hq_cbs_request_submit,
    hq_cbs_requests_list,
    master_template_clone_view,
    master_template_edit_view,
    master_template_list_view,
    master_template_new_view,
    master_template_toggle_active,
)
from apps.inventory.web_views import (
    hq_master_category_edit,
    hq_master_category_list,
    hq_master_category_new,
    hq_master_item_edit,
    hq_master_item_list,
    hq_master_item_new,
    hq_master_uom_edit,
    hq_master_uom_list,
    hq_master_uom_new,
    hq_master_warehouse_edit,
    hq_master_inventory_receipt,
    hq_master_transfer_action,
    hq_master_transfer_list,
    hq_master_transfer_new,
    hq_master_warehouse_stock,
    hq_master_warehouse_list,
    hq_master_warehouse_new,
    hq_master_warehouse_toggle,
)

urlpatterns = [
    path("", include("apps.labor.web_urls")),
    path("cbs/", cbs_list_view),
    path("cbs/new/", cbs_create),
    path("cbs/<int:pk>/edit/", cbs_edit),
    path("cbs/<int:pk>/toggle-active/", cbs_toggle_active),
    path("cbs/<int:pk>/edit-name/", cbs_edit_name),
    path("cbs/<int:pk>/aliases/", cbs_aliases_view),
    path("cbs/<int:pk>/aliases/add/", cbs_alias_add),
    path("cbs/<int:pk>/aliases/<int:alias_id>/set-primary/", cbs_alias_set_primary),
    path("cbs/<int:pk>/aliases/<int:alias_id>/delete/", cbs_alias_delete),
    path("cbs/requests/", hq_cbs_requests_list),
    path("cbs/requests/<int:pk>/", hq_cbs_request_detail),
    path("cbs/requests/<int:pk>/submit/", hq_cbs_request_submit),
    path("templates/", master_template_list_view),
    path("templates/new/", master_template_new_view),
    path("templates/<int:pk>/edit/", master_template_edit_view),
    path("templates/<int:pk>/clone/", master_template_clone_view),
    path("templates/<int:pk>/toggle/", master_template_toggle_active),
    path("warehouses/", hq_master_warehouse_list),
    path("warehouses/receipt/", hq_master_inventory_receipt),
    path("warehouses/transfers/", hq_master_transfer_list),
    path("warehouses/transfers/new/", hq_master_transfer_new),
    path("warehouses/transfers/<int:transfer_id>/<str:action>/", hq_master_transfer_action),
    path("warehouses/<int:warehouse_id>/stock/", hq_master_warehouse_stock),
    path("warehouses/new/", hq_master_warehouse_new),
    path("warehouses/<int:warehouse_id>/edit/", hq_master_warehouse_edit),
    path("warehouses/<int:warehouse_id>/toggle/", hq_master_warehouse_toggle),
    path("items/", hq_master_item_list),
    path("items/new/", hq_master_item_new),
    path("items/<int:item_id>/edit/", hq_master_item_edit),
    path("uom/", hq_master_uom_list),
    path("uom/new/", hq_master_uom_new),
    path("uom/<int:uom_id>/edit/", hq_master_uom_edit),
    path("categories/", hq_master_category_list),
    path("categories/new/", hq_master_category_new),
    path("categories/<int:category_id>/edit/", hq_master_category_edit),
]
