# Generated by Django 5.2.10 on 2026-08-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_owner_confirmation_tax_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashevent',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
