# Generated by Django 5.2.10 on 2026-01-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evidence',
            new_name='evidence_ev_object__e7134e_idx',
            old_name='evidence_obje_4a1c42_idx',
        ),
    ]
