# Generated by Django 5.2.10 on 2026-01-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0002_timesheet'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='laborratetable',
            new_name='labor_labor_labor_r_a4ca68_idx',
            old_name='labor_laborrate_labor_r_b44f8f_idx',
        ),
        migrations.RenameIndex(
            model_name='laborrole',
            new_name='labor_labor_code_540971_idx',
            old_name='labor_laborrole_code_0f66db_idx',
        ),
        migrations.RenameIndex(
            model_name='laborrole',
            new_name='labor_labor_name_560988_idx',
            old_name='labor_laborrole_name_0f2a86_idx',
        ),
        migrations.RenameIndex(
            model_name='laborrole',
            new_name='labor_labor_is_acti_994071_idx',
            old_name='labor_laborrole_is_acti_2c20f3_idx',
        ),
        migrations.RenameIndex(
            model_name='timesheet',
            new_name='labor_times_project_3744d3_idx',
            old_name='labor_timesheet_project_c2df9b_idx',
        ),
        migrations.RenameIndex(
            model_name='timesheet',
            new_name='labor_times_status_a2784a_idx',
            old_name='labor_timesheet_status_4fb338_idx',
        ),
        migrations.RenameIndex(
            model_name='timesheetline',
            new_name='labor_times_timeshe_e1f946_idx',
            old_name='labor_timeshe_timeshe_44c41a_idx',
        ),
        migrations.RenameIndex(
            model_name='timesheetline',
            new_name='labor_times_labor_r_7f6c02_idx',
            old_name='labor_timeshe_labor_r_9d4f22_idx',
        ),
    ]
