# Generated by Django 5.2.10 on 2026-01-28 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0006_costitemalias'),
        ('labor', '0003_rename_labor_laborrate_labor_r_b44f8f_idx_labor_labor_labor_r_a4ca68_idx_and_more'),
        ('projects', '0016_rename_projects_ap_package_3a20c6_idx_projects_ap_package_2176e5_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollBatchNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('last_number', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAllocationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('period_year', models.IntegerField()),
                ('period_month', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=12)),
                ('total_amount', models.BigIntegerField()),
                ('note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_batches_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_batches_created', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_batches_rejected', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year', '-period_month', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAllocationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='labor.payrollallocationbatch')),
                ('cbs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_allocations', to='cost.costitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_allocations', to='projects.project')),
            ],
        ),
        migrations.AddIndex(
            model_name='payrollallocationbatch',
            index=models.Index(fields=['period_year', 'period_month'], name='labor_payro_period__01d5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollallocationbatch',
            index=models.Index(fields=['status'], name='labor_payro_status_362d18_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollallocationbatch',
            constraint=models.UniqueConstraint(fields=('period_year', 'period_month'), name='uniq_payroll_batch_period'),
        ),
        migrations.AddIndex(
            model_name='payrollallocationline',
            index=models.Index(fields=['batch', 'project'], name='labor_payro_batch_i_5333f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollallocationline',
            constraint=models.UniqueConstraint(fields=('batch', 'project'), name='uniq_payroll_batch_project'),
        ),
    ]
