# Generated by Django 5.2.10 on 2026-05-21 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labor", "0004_payrollbatchnumbersequence_payrollallocationbatch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerMaster",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=120)),
                ("rrn_encrypted", models.CharField(blank=True, default="", max_length=255)),
                ("rrn_masked", models.CharField(blank=True, db_index=True, default="", max_length=32)),
                ("identity_hash", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                ("address", models.TextField(blank=True, default="")),
                ("bank_name", models.CharField(blank=True, default="", max_length=120)),
                ("bank_code", models.CharField(blank=True, default="", max_length=30)),
                ("account_number_encrypted", models.CharField(blank=True, default="", max_length=255)),
                ("account_holder", models.CharField(blank=True, default="", max_length=120)),
                ("nationality_code", models.CharField(blank=True, default="", max_length=10)),
                ("visa_code", models.CharField(blank=True, default="", max_length=20)),
                ("comwel_job_code", models.CharField(blank=True, default="", max_length=30)),
                ("cwma_job_name", models.CharField(blank=True, default="", max_length=120)),
                ("retirement_deduction_eligible", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_labor_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worker_masters",
                        to="labor.laborrole",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="workermaster",
            index=models.Index(fields=["name"], name="labor_worke_name_58deb0_idx"),
        ),
        migrations.AddIndex(
            model_name="workermaster",
            index=models.Index(fields=["active"], name="labor_worke_active_c151ec_idx"),
        ),
        migrations.AddIndex(
            model_name="workermaster",
            index=models.Index(fields=["identity_hash"], name="labor_worke_identit_357aa8_idx"),
        ),
    ]
