# Generated by Django 5.2.10 on 2026-05-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost", "0006_costitemalias"),
        ("labor", "0005_workermaster"),
        ("projects", "0016_rename_projects_ap_package_3a20c6_idx_projects_ap_package_2176e5_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaborWorkLedger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("work_date", models.DateField(db_index=True)),
                ("work_month", models.DateField(db_index=True)),
                ("work_unit", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("work_hours", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("unit_wage", models.BigIntegerField(default=0)),
                ("gross_wage", models.BigIntegerField(default=0)),
                ("income_tax", models.BigIntegerField(default=0)),
                ("local_tax", models.BigIntegerField(default=0)),
                ("employment_insurance", models.BigIntegerField(default=0)),
                ("pension", models.BigIntegerField(default=0)),
                ("health_insurance", models.BigIntegerField(default=0)),
                ("net_pay", models.BigIntegerField(default=0)),
                ("detail_work_type", models.CharField(blank=True, default="", max_length=120)),
                ("source", models.CharField(choices=[("MANUAL", "Manual"), ("TIMESHEET", "Timesheet"), ("COST", "Cost")], default="MANUAL", max_length=20)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("CONFIRMED", "Confirmed")], default="DRAFT", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actual_project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="labor_work_ledgers_actual", to="projects.project")),
                ("cost_ref", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="labor_work_ledgers", to="cost.costactual")),
                ("labor_role", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="work_ledgers", to="labor.laborrole")),
                ("report_project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="labor_work_ledgers_report", to="projects.project")),
                ("timesheet_ref", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="work_ledgers", to="labor.timesheet")),
                ("worker", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="work_ledgers", to="labor.workermaster")),
            ],
            options={
                "ordering": ["-work_date", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="laborworkledger",
            index=models.Index(fields=["work_month"], name="labor_labor_work_mo_f61fbe_idx"),
        ),
        migrations.AddIndex(
            model_name="laborworkledger",
            index=models.Index(fields=["worker"], name="labor_labor_worker__a67194_idx"),
        ),
        migrations.AddIndex(
            model_name="laborworkledger",
            index=models.Index(fields=["actual_project"], name="labor_labor_actual__5c75cf_idx"),
        ),
        migrations.AddIndex(
            model_name="laborworkledger",
            index=models.Index(fields=["report_project"], name="labor_labor_report__1ab603_idx"),
        ),
        migrations.AddIndex(
            model_name="laborworkledger",
            index=models.Index(fields=["status"], name="labor_labor_status_a6a8d0_idx"),
        ),
    ]
