# Generated by Django 5.2.10 on 2026-05-21 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labor", "0006_laborworkledger"),
        (
            "projects",
            "0016_rename_projects_ap_package_3a20c6_idx_projects_ap_package_2176e5_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LaborMonthlyPayroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_month", models.DateField(db_index=True)),
                ("total_work_unit", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("gross_wage", models.BigIntegerField(default=0)),
                ("income_tax", models.BigIntegerField(default=0)),
                ("local_tax", models.BigIntegerField(default=0)),
                ("insurance_deductions", models.BigIntegerField(default=0)),
                ("net_pay", models.BigIntegerField(default=0)),
                ("bank_name", models.CharField(blank=True, default="", max_length=120)),
                ("account_number_masked", models.CharField(blank=True, default="", max_length=32)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("PENDING", "미지급"), ("PAID", "지급완료")],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_monthly_payrolls",
                        to="projects.project",
                    ),
                ),
                (
                    "report_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_monthly_payrolls_report",
                        to="projects.project",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_payrolls",
                        to="labor.workermaster",
                    ),
                ),
            ],
            options={
                "ordering": ["-year_month", "worker__name", "project__name", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="labormonthlypayroll",
            constraint=models.UniqueConstraint(
                fields=("year_month", "worker", "project", "report_project"),
                name="uniq_labor_monthly_payroll_scope",
            ),
        ),
    ]
