# Generated by Django 5.2.10 on 2026-06-01 05:30

import apps.labor.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0007_labormonthlypayroll'),
        ('projects', '0017_remove_budgetitem_uq_budgetitem_project_costitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicCardImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(db_index=True)),
                ('cwma_project_name', models.CharField(blank=True, default='', max_length=255)),
                ('deduction_join_no', models.CharField(blank=True, default='', max_length=120)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_file', models.FileField(upload_to=apps.labor.models._electronic_card_upload_to)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', '업로드됨'), ('HEADER_CHECKED', '헤더 확인'), ('PARSE_READY', '파싱 준비'), ('CONFIRMED', '확정'), ('DISCARDED', '폐기')], db_index=True, default='UPLOADED', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('header_check_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronic_card_imports_confirmed', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_card_import_batches', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronic_card_imports_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
                'indexes': [models.Index(fields=['year_month', 'project'], name='labor_elect_year_mo_ef69f0_idx'), models.Index(fields=['status', 'uploaded_at'], name='labor_elect_status_dfbf9e_idx')],
            },
        ),
    ]
