# Generated by Django 5.2.10 on 2026-06-01 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0008_electroniccardimportbatch'),
        ('projects', '0017_remove_budgetitem_uq_budgetitem_project_costitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicCardWorkRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.IntegerField()),
                ('work_month', models.DateField(db_index=True)),
                ('project_name_raw', models.CharField(blank=True, default='', max_length=255)),
                ('deduction_join_no', models.CharField(blank=True, default='', max_length=120)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('worker_name_raw', models.CharField(blank=True, default='', max_length=120)),
                ('rrn_encrypted', models.CharField(blank=True, default='', max_length=255)),
                ('rrn_masked', models.CharField(blank=True, default='', max_length=32)),
                ('identity_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('job_name_raw', models.CharField(blank=True, default='', max_length=120)),
                ('card_issued', models.CharField(blank=True, default='', max_length=60)),
                ('retirement_target', models.CharField(blank=True, default='', max_length=60)),
                ('exclusion_reason', models.CharField(blank=True, default='', max_length=255)),
                ('work_status', models.CharField(blank=True, default='', max_length=120)),
                ('report_status', models.CharField(blank=True, default='', max_length=120)),
                ('error_message', models.TextField(blank=True, default='')),
                ('auto_work_days', models.CharField(blank=True, default='', max_length=40)),
                ('reported_days', models.CharField(blank=True, default='', max_length=40)),
                ('declaration_days', models.CharField(blank=True, default='', max_length=40)),
                ('confirmed_days', models.CharField(blank=True, default='', max_length=40)),
                ('day_01', models.CharField(blank=True, default='', max_length=16)),
                ('day_02', models.CharField(blank=True, default='', max_length=16)),
                ('day_03', models.CharField(blank=True, default='', max_length=16)),
                ('day_04', models.CharField(blank=True, default='', max_length=16)),
                ('day_05', models.CharField(blank=True, default='', max_length=16)),
                ('day_06', models.CharField(blank=True, default='', max_length=16)),
                ('day_07', models.CharField(blank=True, default='', max_length=16)),
                ('day_08', models.CharField(blank=True, default='', max_length=16)),
                ('day_09', models.CharField(blank=True, default='', max_length=16)),
                ('day_10', models.CharField(blank=True, default='', max_length=16)),
                ('day_11', models.CharField(blank=True, default='', max_length=16)),
                ('day_12', models.CharField(blank=True, default='', max_length=16)),
                ('day_13', models.CharField(blank=True, default='', max_length=16)),
                ('day_14', models.CharField(blank=True, default='', max_length=16)),
                ('day_15', models.CharField(blank=True, default='', max_length=16)),
                ('day_16', models.CharField(blank=True, default='', max_length=16)),
                ('day_17', models.CharField(blank=True, default='', max_length=16)),
                ('day_18', models.CharField(blank=True, default='', max_length=16)),
                ('day_19', models.CharField(blank=True, default='', max_length=16)),
                ('day_20', models.CharField(blank=True, default='', max_length=16)),
                ('day_21', models.CharField(blank=True, default='', max_length=16)),
                ('day_22', models.CharField(blank=True, default='', max_length=16)),
                ('day_23', models.CharField(blank=True, default='', max_length=16)),
                ('day_24', models.CharField(blank=True, default='', max_length=16)),
                ('day_25', models.CharField(blank=True, default='', max_length=16)),
                ('day_26', models.CharField(blank=True, default='', max_length=16)),
                ('day_27', models.CharField(blank=True, default='', max_length=16)),
                ('day_28', models.CharField(blank=True, default='', max_length=16)),
                ('day_29', models.CharField(blank=True, default='', max_length=16)),
                ('day_30', models.CharField(blank=True, default='', max_length=16)),
                ('day_31', models.CharField(blank=True, default='', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('match_status', models.CharField(choices=[('MATCHED', '매칭'), ('UNMATCHED', '미매칭')], db_index=True, default='UNMATCHED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_rows', to='labor.electroniccardimportbatch')),
                ('matched_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronic_card_raw_rows', to='labor.workermaster')),
            ],
            options={
                'ordering': ['row_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicCardWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('card_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_worked', models.BooleanField(default=False)),
                ('match_status', models.CharField(choices=[('MATCHED', '매칭'), ('UNMATCHED', '미매칭')], db_index=True, default='UNMATCHED', max_length=12)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_rows', to='labor.electroniccardimportbatch')),
                ('card_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronic_card_day_rows', to='projects.project')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronic_card_day_rows', to='labor.workermaster')),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='labor.electroniccardworkraw')),
            ],
            options={
                'ordering': ['work_date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='electroniccardworkraw',
            index=models.Index(fields=['batch', 'work_month'], name='labor_elect_batch_i_c0d746_idx'),
        ),
        migrations.AddIndex(
            model_name='electroniccardworkraw',
            index=models.Index(fields=['batch', 'identity_hash', 'match_status'], name='labor_elect_batch_i_2d2ce3_idx'),
        ),
        migrations.AddConstraint(
            model_name='electroniccardworkraw',
            constraint=models.UniqueConstraint(fields=('batch', 'row_no'), name='uniq_electronic_card_work_raw_row'),
        ),
        migrations.AddIndex(
            model_name='electroniccardworkday',
            index=models.Index(fields=['batch', 'work_date'], name='labor_elect_batch_i_fa7c60_idx'),
        ),
        migrations.AddIndex(
            model_name='electroniccardworkday',
            index=models.Index(fields=['batch', 'worker', 'match_status'], name='labor_elect_batch_i_34c0f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='electroniccardworkday',
            constraint=models.UniqueConstraint(fields=('raw', 'work_date'), name='uniq_electronic_card_work_day_scope'),
        ),
    ]
