# Generated by Django 5.2.10 on 2026-06-01 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0009_electroniccardworkraw_electroniccardworkday_and_more'),
        ('projects', '0017_remove_budgetitem_uq_budgetitem_project_costitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(db_index=True)),
                ('work_date', models.DateField(db_index=True)),
                ('erp_work_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card_work_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('MATCH', '일치'), ('ERP_ONLY', 'ERP만 있음'), ('CARD_ONLY', '전자카드만 있음'), ('DIFF', '공수 차이'), ('UNMATCHED', '미매칭'), ('RESOLVED', '해결됨')], db_index=True, default='DIFF', max_length=16)),
                ('resolution', models.CharField(blank=True, choices=[('ERP', 'ERP 기준'), ('CARD', '전자카드 기준'), ('MANUAL', '수동 확인'), ('EXCLUDED', '제외')], default='', max_length=16)),
                ('final_work_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hq_comment', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('export_included', models.BooleanField(default=True)),
                ('export_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('export_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_results', to='labor.electroniccardimportbatch')),
                ('card_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_results', to='labor.electroniccardworkday')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_reconciliation_results', to='projects.project')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_reconciliation_results_resolved', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_reconciliation_results', to='labor.workermaster')),
            ],
            options={
                'ordering': ['work_date', 'worker_id', 'id'],
                'indexes': [models.Index(fields=['batch', 'year_month', 'project'], name='labor_labor_batch_i_a70b18_idx'), models.Index(fields=['batch', 'worker', 'work_date', 'status'], name='labor_labor_batch_i_269529_idx')],
            },
        ),
    ]
