# Generated by Django 5.2.10 on 2026-06-02 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0010_laborreconciliationresult'),
        ('projects', '0017_remove_budgetitem_uq_budgetitem_project_costitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborConfirmedWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(db_index=True)),
                ('work_date', models.DateField(db_index=True)),
                ('final_work_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('source_basis', models.CharField(choices=[('ERP', 'ERP'), ('CARD', '전자카드'), ('MANUAL', '수동확정'), ('EXCLUDED', '제외')], default='ERP', max_length=16)),
                ('export_included', models.BooleanField(default=True)),
                ('export_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('export_note', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labor_confirmed_work_days_actual', to='projects.project')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_work_days', to='labor.electroniccardimportbatch')),
                ('card_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_confirmed_work_days_card', to='projects.project')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_confirmed_work_days_confirmed', to=settings.AUTH_USER_MODEL)),
                ('reconciliation_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_work_days', to='labor.laborreconciliationresult')),
                ('report_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_confirmed_work_days_report', to='projects.project')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_work_days', to='labor.workermaster')),
            ],
            options={
                'ordering': ['work_date', 'worker_id', 'id'],
                'indexes': [models.Index(fields=['year_month', 'worker', 'report_project', 'work_date'], name='labor_labor_year_mo_ab6ab8_idx'), models.Index(fields=['batch', 'source_basis', 'export_included'], name='labor_labor_batch_i_83d124_idx')],
                'constraints': [models.UniqueConstraint(fields=('reconciliation_result',), name='uniq_labor_confirmed_work_day_result')],
            },
        ),
    ]
