# Generated by Django 5.2.10 on 2026-06-02 02:22

import apps.labor.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0011_laborconfirmedworkday'),
        ('projects', '0017_remove_budgetitem_uq_budgetitem_project_costitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborExcelExportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('CWMA_CARD_REUPLOAD', 'CWMA 전자카드 재업로드')], db_index=True, default='CWMA_CARD_REUPLOAD', max_length=32)),
                ('year_month', models.DateField(db_index=True)),
                ('generated_file', models.FileField(upload_to=apps.labor.models._labor_excel_export_upload_to)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('generated_filename', models.CharField(blank=True, default='', max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('GENERATED', '생성됨'), ('DOWNLOADED', '다운로드됨'), ('DISCARDED', '폐기')], db_index=True, default='GENERATED', max_length=16)),
                ('changed_count', models.IntegerField(default=0)),
                ('included_count', models.IntegerField(default=0)),
                ('excluded_count', models.IntegerField(default=0)),
                ('total_export_work_unit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_excel_exports_downloaded', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_excel_exports_generated', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_excel_exports', to='projects.project')),
                ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_exports', to='labor.electroniccardimportbatch')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
                'indexes': [models.Index(fields=['export_type'], name='labor_labor_export__27c4f0_idx'), models.Index(fields=['year_month'], name='labor_labor_year_mo_f0f2e3_idx'), models.Index(fields=['project'], name='labor_labor_project_523dda_idx'), models.Index(fields=['source_batch'], name='labor_labor_source__c767de_idx'), models.Index(fields=['status'], name='labor_labor_status_8bc492_idx')],
            },
        ),
    ]
