# Generated by Django 5.2.10 on 2026-01-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectassignment_role_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectassignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectassignment',
            name='role_in_project',
        ),
    ]
