# Generated by Django 5.2.10 on 2026-08-27 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projectassignment_assignment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntityLicenseConstructionPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_category', models.CharField(max_length=120)),
                ('external_category_code', models.CharField(blank=True, default='', max_length=60)),
                ('as_of_date', models.DateField(help_text='3년·5년 실적을 산정한 기준일')),
                ('three_year_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('five_year_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('source', models.CharField(choices=[('MANUAL', '수기 입력'), ('CERTIFICATE', '실적증명서'), ('API', '외부 API'), ('IMPORT', '파일 가져오기')], default='MANUAL', max_length=16)),
                ('evidence_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_legal_entity_license_performances', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='construction_performances', to='core.legalentitylicense')),
            ],
            options={
                'ordering': ['-as_of_date', 'license__license_type', 'work_category'],
                'indexes': [models.Index(fields=['license', 'as_of_date'], name='core_legale_license_0a03ac_idx'), models.Index(fields=['external_category_code', 'as_of_date'], name='core_legale_externa_681e32_idx')],
                'constraints': [models.UniqueConstraint(fields=('license', 'work_category', 'as_of_date'), name='uniq_license_work_category_performance_snapshot')],
            },
        ),
    ]
