# Generated by Django 5.2.10 on 2026-08-27 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_legalentitylicenseconstructionperformanceevidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntityCreditRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_agency', models.CharField(max_length=120)),
                ('rating_grade', models.CharField(max_length=40)),
                ('assessed_on', models.DateField(help_text='신용평가 기준일 또는 발급일')),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('evidence_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_legal_entity_credit_ratings', to=settings.AUTH_USER_MODEL)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_ratings', to='core.legalentity')),
            ],
            options={
                'ordering': ['-assessed_on', 'rating_agency'],
                'indexes': [models.Index(fields=['legal_entity', 'valid_until'], name='core_legale_legal_e_ae4f40_idx')],
                'constraints': [models.UniqueConstraint(fields=('legal_entity', 'rating_agency', 'assessed_on'), name='uniq_legal_entity_credit_rating_snapshot')],
            },
        ),
    ]
