# Generated by Django 5.2.10 on 2026-01-26 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_master'),
        ('projects', '0016_rename_projects_ap_package_3a20c6_idx_projects_ap_package_2176e5_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('ISSUE', 'Issue'), ('ADJUST', 'Adjust')], max_length=20)),
                ('tx_date', models.DateField()),
                ('qty_delta', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_cost', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('ref_type', models.CharField(choices=[('MANUAL', 'Manual'), ('TRANSFER', 'Transfer'), ('ISSUE_TO_WORK', 'Issue to work'), ('PURCHASE', 'Purchase')], default='MANUAL', max_length=20)),
                ('ref_id', models.BigIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='warehouse',
            name='chk_warehouse_type_project',
        ),
        migrations.RenameIndex(
            model_name='itemcategory',
            new_name='inventory_i_name_0c36a8_idx',
            old_name='inventory_it_name_e090e7_idx',
        ),
        migrations.RenameIndex(
            model_name='itemcategory',
            new_name='inventory_i_code_ac611a_idx',
            old_name='inventory_it_code_3ef282_idx',
        ),
        migrations.RenameIndex(
            model_name='itemmaster',
            new_name='inventory_i_code_a374c0_idx',
            old_name='inventory_it_code_5c1b75_idx',
        ),
        migrations.RenameIndex(
            model_name='itemmaster',
            new_name='inventory_i_name_bfbfda_idx',
            old_name='inventory_it_name_9a9db0_idx',
        ),
        migrations.RenameIndex(
            model_name='itemmaster',
            new_name='inventory_i_barcode_2416ad_idx',
            old_name='inventory_it_barco_5c0c42_idx',
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='inventory_l_warehou_aa4cb9_idx',
            old_name='inventory_lo_warehou_987f80_idx',
        ),
        migrations.RenameIndex(
            model_name='uom',
            new_name='inventory_u_code_832a27_idx',
            old_name='inventory_uo_code_0a9a7a_idx',
        ),
        migrations.RenameIndex(
            model_name='warehouse',
            new_name='inventory_w_warehou_a1ac57_idx',
            old_name='inventory_wa_warehou_1c7a1b_idx',
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('project__isnull', True), ('warehouse_type', 'hq')), models.Q(('project__isnull', False), ('warehouse_type', 'site')), _connector='OR'), name='chk_warehouse_type_project'),
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_ledgers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.itemmaster'),
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.uom'),
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stock',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.itemmaster'),
        ),
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.warehouse'),
        ),
        migrations.AddIndex(
            model_name='inventoryledger',
            index=models.Index(fields=['tx_date', 'warehouse'], name='inventory_i_tx_date_eba51a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryledger',
            index=models.Index(fields=['item', 'tx_date'], name='inventory_i_item_id_b85aef_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['warehouse', 'item'], name='inventory_s_warehou_7eab38_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'location', 'item'), name='uq_stock_warehouse_location_item'),
        ),
    ]
