# Generated by Django 5.2.10 on 2026-01-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_issue_to_work'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='issuetowork',
            new_name='inventory_i_project_2c96c9_idx',
            old_name='inventory_i_project_8f7e2c_idx',
        ),
        migrations.RenameIndex(
            model_name='issuetowork',
            new_name='inventory_i_status_114f56_idx',
            old_name='inventory_i_status_8dfd9d_idx',
        ),
        migrations.RenameIndex(
            model_name='issuetoworkline',
            new_name='inventory_i_issue_i_2b6d63_idx',
            old_name='inventory_i_issue_4a4fe1_idx',
        ),
        migrations.RenameIndex(
            model_name='transfer',
            new_name='inventory_t_project_cc7c90_idx',
            old_name='inventory_t_project_3a1cfb_idx',
        ),
        migrations.RenameIndex(
            model_name='transfer',
            new_name='inventory_t_tx_date_9f276a_idx',
            old_name='inventory_t_tx_date_3e50aa_idx',
        ),
        migrations.RenameIndex(
            model_name='transferline',
            new_name='inventory_t_transfe_25692f_idx',
            old_name='inventory_t_transfer_21960b_idx',
        ),
    ]
