# Generated by Django 5.2.10 on 2026-08-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cost", "0006_costitemalias"),
        ("inventory", "0006_rename_inventory_i_project_8f7e2c_idx_inventory_i_project_2c96c9_idx_and_more"),
        ("projects", "0017_remove_budgetitem_uq_budgetitem_project_costitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMaterialRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_name", models.CharField(max_length=120)),
                ("spec", models.TextField(blank=True, default="")),
                ("uom_text", models.CharField(default="EA", max_length=10)),
                ("requested_qty", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("submitted", "SUBMITTED"), ("approved", "APPROVED"), ("rejected", "REJECTED")], default="submitted", max_length=16)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reject_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_cbs", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_project_materials", to="cost.costitem")),
                ("approved_item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_project_material_requests", to="inventory.itemmaster")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="material_requests", to="projects.project")),
                ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requested_project_materials", to=settings.AUTH_USER_MODEL)),
                ("requested_cbs", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requested_project_materials", to="cost.costitem")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_project_materials", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [models.Index(fields=["project", "status"], name="inventory_p_project_58a141_idx"), models.Index(fields=["status", "requested_at"], name="inventory_p_status_a68794_idx")],
            },
        ),
    ]
