# Generated by Django 5.2.10 on 2026-08-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_sync_issuetowork_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetowork',
            name='status',
            field=models.CharField(choices=[('DRAFT', '임시저장'), ('SUBMITTED', '제출'), ('APPROVED', '승인'), ('REJECTED', '반려')], default='DRAFT', max_length=16),
        ),
    ]
