# Generated by Django 5.2.10 on 2026-08-26 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0009_cost_actual_line_vat_split'),
        ('evidence', '0003_evidence_status'),
        ('field', '0003_retroactiveentryrequest'),
        ('inventory', '0012_alter_warehouse_legal_entity'),
        ('projects', '0023_project_contracting_licenses_project_work_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDailyLogWorkLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('prior_approved_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('today_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('cumulative_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('today_work', models.TextField(blank=True, default='')),
                ('tomorrow_work', models.TextField(blank=True, default='')),
                ('special_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', '임시저장'), ('SUBMITTED', '제출'), ('APPROVED', '승인'), ('REJECTED', '반려')], default='DRAFT', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('approval_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_daily_logs_approved', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_daily_logs', to='projects.project')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_daily_logs_rejected', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_daily_logs_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteDailyLogCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_snapshot', models.JSONField(default=dict)),
                ('proposed_payload', models.JSONField(default=dict)),
                ('impact_snapshot', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', '임시저장'), ('SUBMITTED', '승인 대기'), ('APPROVED', '승인'), ('REJECTED', '반려')], default='DRAFT', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_daily_log_corrections_approved', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_daily_log_corrections_rejected', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_daily_log_corrections_requested', to=settings.AUTH_USER_MODEL)),
                ('site_daily_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='field.sitedailylog')),
            ],
        ),
        migrations.CreateModel(
            name='SiteDailyLogEquipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=120)),
                ('specification', models.CharField(blank=True, default='', max_length=120)),
                ('usage_unit', models.CharField(choices=[('UNIT', '대'), ('HOUR', '시간'), ('DAY', '일'), ('COUNT', '회')], max_length=10)),
                ('ownership_type', models.CharField(choices=[('OWNED', '자체'), ('RENTED', '임차')], default='RENTED', max_length=10)),
                ('today_usage_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('cumulative_usage_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('memo', models.TextField(blank=True, default='')),
                ('cost_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cost.costactual')),
                ('site_daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_lines', to='field.sitedailylog')),
            ],
        ),
        migrations.CreateModel(
            name='SiteDailyLogEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, default='', max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evidence.evidence')),
                ('site_daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='field.sitedailylog')),
            ],
        ),
        migrations.CreateModel(
            name='SiteDailyLogReceiptRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=30)),
                ('qty_snapshot', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('amount_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryledger')),
                ('site_daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_refs', to='field.sitedailylog')),
            ],
        ),
    ]
