# Generated by Django 5.2.10 on 2026-08-26 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0004_sitedailylogworkline_sitedailylog_and_more'),
        ('inventory', '0012_alter_warehouse_legal_entity'),
        ('projects', '0024_projectworkprogressmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedailylogworkline',
            name='progress_mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projectworkprogressmapping'),
        ),
        migrations.AddField(
            model_name='sitedailylogworkline',
            name='site_daily_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_lines', to='field.sitedailylog'),
        ),
        migrations.AddField(
            model_name='sitedailylogworkline',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.uom'),
        ),
        migrations.AddIndex(
            model_name='sitedailylog',
            index=models.Index(fields=['project', 'report_date', 'status'], name='field_sited_project_88bf62_idx'),
        ),
        migrations.AddConstraint(
            model_name='sitedailylog',
            constraint=models.UniqueConstraint(fields=('project', 'report_date'), name='uq_site_daily_log_project_date'),
        ),
        migrations.AddIndex(
            model_name='sitedailylogcorrectionrequest',
            index=models.Index(fields=['project', 'status'], name='field_sited_project_62447b_idx'),
        ),
        migrations.AddConstraint(
            model_name='sitedailylogcorrectionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED'])), fields=('site_daily_log',), name='uq_active_site_daily_log_correction'),
        ),
        migrations.AddIndex(
            model_name='sitedailylogequipmentline',
            index=models.Index(fields=['site_daily_log', 'equipment_name'], name='field_sited_site_da_332c20_idx'),
        ),
        migrations.AddConstraint(
            model_name='sitedailylogequipmentline',
            constraint=models.CheckConstraint(condition=models.Q(('today_usage_qty__gte', 0)), name='chk_site_daily_log_equipment_today_qty_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sitedailylogevidence',
            constraint=models.UniqueConstraint(fields=('site_daily_log', 'evidence'), name='uq_site_daily_log_evidence'),
        ),
        migrations.AddConstraint(
            model_name='sitedailylogreceiptref',
            constraint=models.UniqueConstraint(fields=('site_daily_log', 'inventory_ledger'), name='uq_site_daily_log_receipt_ledger'),
        ),
        migrations.AddConstraint(
            model_name='sitedailylogworkline',
            constraint=models.UniqueConstraint(fields=('site_daily_log', 'progress_mapping'), name='uq_site_daily_log_work_line_mapping'),
        ),
        migrations.AddConstraint(
            model_name='sitedailylogworkline',
            constraint=models.CheckConstraint(condition=models.Q(('today_qty__gte', 0)), name='chk_site_daily_log_work_line_today_qty_nonnegative'),
        ),
    ]
