# Generated by Django 5.2.10 on 2026-05-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_daily_progress_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogress',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
