# Generated by Django 5.2.10 on 2026-01-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closing', '0002_adjustment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adjustment',
            new_name='closing_adj_project_78a5fe_idx',
            old_name='closing_adj_project_period_idx',
        ),
        migrations.RenameIndex(
            model_name='adjustment',
            new_name='closing_adj_status_4e43f7_idx',
            old_name='closing_adj_status_type_idx',
        ),
    ]
