# Generated by Django 5.1.7 on 2026-01-28 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closing', '0003_rename_closing_adj_project_period_idx_closing_adj_project_78a5fe_idx_and_more'),
        ('projects', '0016_rename_projects_ap_package_3a20c6_idx_projects_ap_package_2176e5_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSING', 'Closing'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('close_effective_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_projects', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='close', to='projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project',), name='uniq_project_close_project')],
            },
        ),
    ]
