# Generated by Django 5.2.10 on 2026-01-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='riskevent',
            new_name='risk_riskev_event_t_2f19b0_idx',
            old_name='risk_riske_event_t_d1b177_idx',
        ),
        migrations.RenameIndex(
            model_name='riskevent',
            new_name='risk_riskev_object__d09b47_idx',
            old_name='risk_riske_object__843a6d_idx',
        ),
    ]
