# Generated by Django 5.2.10 on 2026-01-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_master_templates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='masterbudgettemplateitem',
            new_name='master_mast_templat_54a0bb_idx',
            old_name='master_mas_template_8dc4c0_idx',
        ),
        migrations.RenameIndex(
            model_name='mastertemplate',
            new_name='master_mast_categor_e9f36f_idx',
            old_name='master_mas_category_17b73b_idx',
        ),
        migrations.RenameIndex(
            model_name='masterwbstemplateitem',
            new_name='master_mast_templat_470847_idx',
            old_name='master_mas_template_9a8c33_idx',
        ),
    ]
